/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthConfig: typeof import('./src/components/PostMan/AuthConfig.vue')['default']
    ColorPass: typeof import('./src/components/ColorPass/index.vue')['default']
    DateConverter: typeof import('./src/components/DateConverter/index.vue')['default']
    EnvironmentVariables: typeof import('./src/components/PostMan/EnvironmentVariables.vue')['default']
    IconInbox: typeof import('./src/components/ImageCompressor/IconInbox.vue')['default']
    IconReset: typeof import('./src/components/ImageCompressor/IconReset.vue')['default']
    ImageCompressor: typeof import('./src/components/ImageCompressor/index.vue')['default']
    JsonCtn: typeof import('./src/components/JsonCtn/index.vue')['default']
    LangTranslator: typeof import('./src/components/LangTranslator/index.vue')['default']
    LinuxCommand: typeof import('./src/components/LinuxCommand/index.vue')['default']
    PageScreenshot: typeof import('./src/components/PageScreenshot/index.vue')['default']
    PostManMain: typeof import('./src/components/PostMan/PostManMain.vue')['default']
    QRCode: typeof import('./src/components/QRCode/index.vue')['default']
    RemarkInfos: typeof import('./src/components/ColorPass/RemarkInfos.vue')['default']
    RequestBody: typeof import('./src/components/PostMan/RequestBody.vue')['default']
    RequestHeaders: typeof import('./src/components/PostMan/RequestHeaders.vue')['default']
    RequestHistory: typeof import('./src/components/PostMan/RequestHistory.vue')['default']
    RequestPanel: typeof import('./src/components/PostMan/RequestPanel.vue')['default']
    ResponseViewer: typeof import('./src/components/PostMan/ResponseViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgEditor: typeof import('./src/components/SvgEditor/index.vue')['default']
    TechStackDetection: typeof import('./src/components/TechStackDetection/index.vue')['default']
    UnitCalculator: typeof import('./src/components/UnitCalculator/index.vue')['default']
  }
}
